export const partnersImages = [
  {
    srcM: '/images/partners/partner_01m.jpg',
    id: '01',
    wM: 66,
    hM: 66,
    srcT: '/images/partners/partner_01t.jpg',
    wT: 66,
    hT: 66,
    srcD: '/images/partners/partner_01d.jpg',
    wD: 104,
    hD: 104,
  },
  {
    srcM: '/images/partners/partner_02m.jpg',
    id: '02',
    wM: 98,
    hM: 32,
    srcT: '/images/partners/partner_02t.jpg',
    wT: 98,
    hT: 32,
    srcD: '/images/partners/partner_02d.jpg',
    wD: 154,
    hD: 50,
  },
  {
    srcM: '/images/partners/partner_03m.jpg',
    id: '03',
    wM: 84,
    hM: 52,
    srcT: '/images/partners/partner_03t.jpg',
    wT: 84,
    hT: 52,
    srcD: '/images/partners/partner_03d.jpg',
    wD: 130,
    hD: 80,
  },
  {
    srcM: '/images/partners/partner_04m.jpg',
    id: '04',
    wM: 96,
    hM: 56,
    srcT: '/images/partners/partner_04t.jpg',
    wT: 96,
    hT: 56,
    srcD: '/images/partners/partner_04d.jpg',
    wD: 149,
    hD: 88,
  },
  {
    srcM: '/images/partners/partner_05m.jpg',
    id: '05',
    wM: 66,
    hM: 66,
    srcT: '/images/partners/partner_05t.jpg',
    wT: 66,
    hT: 66,
    srcD: '/images/partners/partner_05d.jpg',
    wD: 102,
    hD: 102,
  },
];
